#
#             __       __    __    ______  __  ___ ____    ____ .______    __        ______     ______  __  ___
#            |  |     |  |  |  |  /      ||  |/  / \   \  /   / |   _  \  |  |      /  __  \   /      ||  |/  /
#   ,---.    |  |     |  |  |  | |  ,----'|  '  /   \   \/   /  |  |_)  | |  |     |  |  |  | |  ,----'|  '  /
#  | .-. :   |  |     |  |  |  | |  |     |    <     \_    _/   |   _  <  |  |     |  |  |  | |  |     |    <
#  \   --.   |  `----.|  `--'  | |  `----.|  .  \      |  |     |  |_)  | |  `----.|  `--'  | |  `----.|  .  \
#   `----'   |_______| \______/   \______||__|\__\     |__|     |______/  |_______| \______/   \______||__|\__\
#
#
#
#   Version: 2.0 | Recoded Version
#   Configuration
#
#   Wiki: https://zs0bye.gitbook.io/eluckyblock/plugins/eluckyblock-free
#


#  _________                              ______
#  __  ____/_____________________________ ___  /
#  _  / __ _  _ \_  __ \  _ \_  ___/  __ `/_  /
#  / /_/ / /  __/  / / /  __/  /   / /_/ /_  /
#  \____/  \___//_/ /_/\___//_/    \__,_/ /_/
#
Settings:
  prefix: ' &d❏ ₑLuckyBlock ┃ &7'
  # Available languages: en_US, it_IT
  locale: en_US
  check_update:
    enabled: true
    # Types Available: NORMAL, DOWNLOAD
    type: NORMAL
  hooks:
    PlaceholderAPI: false
    WorldGuard: false
    WorldEdit: false
    Vault: false
    PlotSquared: false


#  ____________
#  __  ___/_  /___________________ _______ _____
#  _____ \_  __/  __ \_  ___/  __ `/_  __ `/  _ \
#  ____/ // /_ / /_/ /  /   / /_/ /_  /_/ //  __/
#  /____/ \__/ \____//_/    \__,_/ _\__, / \___/
#                                  /____/
Storage:
  # Types Available: SQLite, MySQL
  type: SQLite
  mysql:
    database: eLuckyBlock
    hostname: localhost
    port: 3306
    user: root
    password: 'MyPassword'
    advanced:
      customURI: '?useSSL=false&autoReconnect=true'
  pool_settings:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000