name: eLuckyBlock
main: it.zS0bye.eLuckyBlock.ELuckyBlock
softdepend: [PlaceholderAPI, WorldGuard, WorldEdit, Vault, TokenEnchant, TokenManager, PlotSquared]
version: '${project.version}'
api-version: 1.13
author: zS0bye
description: The LuckyBlock Plugin you needed! For Prison, SkyBlock, etc..
commands:
  eluckyblock:
    description: Main command of eLuckyBlock
    aliases: [eluckyblocks, luckyblock, luckyblocks, elb, lb]
permissions:
  eluckyblock.*:
    description: Gives access to all eLuckyBlock permissions
    children:
      luckyblock.command: true
      luckyblock.command.*: true
  eluckyblock.bypass.gamemode:
    description: Allow to bypass gamemode check
    default: false
  eluckyblock.command.*:
    description: Gives access to all eLuckyBlock commands
    children:
      eluckyblock.command: true
      eluckyblock.command.reload: true
      eluckyblock.command.info: true
      eluckyblock.command.info.others: true
      eluckyblock.command.give: true
      eluckyblock.command.citem: true
  eluckyblock.command:
    description: Allow to use eLuckyBlock command
    default: op
  eluckyblock.command.reload:
    description: Allow to use reload command
    default: op
  eluckyblock.command.info:
    description: Allow to use info command
    default: true
  eluckyblock.command.info.others:
    description: Allow to use info others command
    default: op
  eluckyblock.command.give:
    description: Allow to use give command
    default: op
  eluckyblock.command.citem:
    description: Allow to use citem command
    default: op